#!/bin/sh
#
# This script is executed in the post-removal phase
#
#   On Debian,
#       $1=remove    : indicates a removal
#       $1=purge     : indicates an upgrade
#
set -e

SOURCE_ENV_FILE=true
REMOVE_DIRS=false
REMOVE_SERVICE=false
REMOVE_USER_AND_GROUP=false

case "$1" in

    # Debian ####################################################
    remove)
        REMOVE_DIRS=true
        REMOVE_SERVICE=true
    ;;

    purge)
        REMOVE_USER_AND_GROUP=true
        SOURCE_ENV_FILE=false
    ;;
    failed-upgrade|abort-install|abort-upgrade|disappear|upgrade|disappear)
    ;;

    *)
        echo "post remove script called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

# Sets the default values for ${appName} variables used in this script
APP_USER="${packaging.user}"
APP_GROUP="${packaging.group}"
LOG_DIR="${packaging.log.dir}"
PID_DIR="${packaging.pid.dir}"
DATA_DIR="${packaging.data.dir}"

# Source the default env file
if [ "$SOURCE_ENV_FILE" = "true" ]; then
    APP_ENV_FILE="/etc/default/${appName}"
    if [ -f "$APP_ENV_FILE" ]; then
        . "$APP_ENV_FILE"
    fi
fi

if [ "$REMOVE_SERVICE" = "true" ]; then
    if command -v systemctl >/dev/null; then
        systemctl --no-reload disable ${appName}.service > /dev/null 2>&1 || true
    fi

    if command -v update-rc.d >/dev/null; then
        update-rc.d ${appName} remove >/dev/null || true
    fi
fi

if [ "$REMOVE_DIRS" = "true" ]; then

    if [ -d "$LOG_DIR" ]; then
        echo -n "Deleting log directory..."
        rm -rf "$LOG_DIR"
        echo " OK"
    fi

    if [ -d "$PID_DIR" ]; then
        echo -n "Deleting PID directory..."
        rm -rf "$PID_DIR"
        echo " OK"
    fi

    # Delete the data directory if and only if empty
    if [ -d "$DATA_DIR" ]; then
        rmdir --ignore-fail-on-non-empty "$DATA_DIR"
    fi
fi

if [ "$REMOVE_USER_AND_GROUP" = "true" ]; then
    if id "$APP_USER" > /dev/null 2>&1 ; then
        userdel "$APP_USER"
    fi

    if getent group "$APP_GROUP" > /dev/null 2>&1 ; then
        groupdel "$APP_GROUP"
    fi
fi

# vi:ai sw=4 ts=4 tw=0 et